import type { GetServerSidePropsContext, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { v4 } from 'uuid';
import { serialize } from 'cookie';
import { SplitFactory } from '@splitsoftware/splitio';

import styles from '../styles/Home.module.css'
import getConfig from 'next/config';

type Props = {
  splits: { [key: string]: string };
};

const Home: NextPage<Props> = (props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {props.splits.W3W_WEB_COMPONENTS === 'on' ? (
          <>
            <h1 className={styles.title}>
              Welcome to <a href="https://nextjs.org">Next.js!</a>
            </h1>

            <p className={styles.description}>
              Get started by editing{' '}
              <code className={styles.code}>pages/index.tsx</code>
            </p>

            <div className={styles.grid}>
              <a href="https://nextjs.org/docs" className={styles.card}>
                <h2>Documentation &rarr;</h2>
                <p>Find in-depth information about Next.js features and API.</p>
              </a>

              <a href="https://nextjs.org/learn" className={styles.card}>
                <h2>Learn &rarr;</h2>
                <p>Learn about Next.js in an interactive course with quizzes!</p>
              </a>

              <a
                href="https://github.com/vercel/next.js/tree/canary/examples"
                className={styles.card}
              >
                <h2>Examples &rarr;</h2>
                <p>Discover and deploy boilerplate example Next.js projects.</p>
              </a>

              <a
                href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                className={styles.card}
              >
                <h2>Deploy &rarr;</h2>
                <p>
                  Instantly deploy your Next.js site to a public URL with Vercel.
                </p>
              </a>
            </div>
          </>
        ): null}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getServerSideProps(ctx: GetServerSidePropsContext) {
  const { serverRuntimeConfig } = getConfig();
  const key = ctx.req.cookies.device_id || v4();
  const factory = SplitFactory({
    core: {
      authorizationKey: serverRuntimeConfig.SPLIT_SERVER_SIDE_KEY,
    },
  });
  const client = factory.client();

  const splits = await new Promise((res) => {
    client.on(client.Event.SDK_READY, function() {
      res(client.getTreatments(key, ['W3W_WEB_COMPONENTS']));
    });
  });

  ctx.res.setHeader('Set-Cookie', [serialize('device_id', key, {
    maxAge: 60 * 60 * 24 * 365, // 1 year
    path: '/',
    sameSite: 'strict',
  })]);

  client.destroy();

  console.log('device_id', key)
  console.log('treatments', {
    splits
  });

  return {
    props: {
      splits,
    },
  };
}

export default Home
